#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const IMG_DIR = path.join(ROOT, 'assets', 'img');

// Wikimedia yêu cầu User-Agent phải kèm email hoặc thông tin liên hệ rõ ràng
const UA = process.env.SPLENDOR_UA ||
  'SplendorWebArtFetcher/1.1 (https://github.com/trinhphamtrunghieu/Splendor; contact: your-email@example.com)';

const NOBLES = {
  n1: { name: 'Mary Stuart', titles: ['Mary, Queen of Scots'] },
  n2: { name: 'Charles V', titles: ['Charles V, Holy Roman Emperor'] },
  n3: { name: 'Machiavelli', titles: ['Niccolò Machiavelli'] },
  n4: { name: 'Isabella I', titles: ['Isabella I of Castile'] },
  n5: { name: 'Suleiman', titles: ['Suleiman the Magnificent'] },
  n6: { name: 'Catherine de Medici', titles: ['Catherine de\' Medici'] },
  n7: { name: 'Anne of Brittany', titles: ['Anne of Brittany', 'Anne, Duchess of Brittany'] },
  n8: {
    name: 'Elisabeth of Austria',
    titles: ['Elisabeth of Austria, Queen of France', 'Elisabeth of Austria (1554–1592)']
  },
  n9: { name: 'Francis I of France', titles: ['Francis I of France'] },
  n10: { name: 'Henry VIII', titles: ['Henry VIII'] }
};

const GEM_QUERIES = {
  white: 'diamond cut gemstone loose stone',
  blue: 'sapphire cut gemstone loose stone',
  green: 'emerald cut gemstone loose stone',
  red: 'ruby cut gemstone loose stone',
  black: 'onyx polished gemstone cabochon',
  gold: 'gold coin ducat obverse'
};

/* ------------------------------------------------------------- helpers */

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function isFreeLicense(shortName) {
  if (!shortName) return false;
  const s = String(shortName).toLowerCase();
  if (/fair use|non-free|nonfree|all rights reserved|copyright/.test(s)) return false;
  if (/\bnc\b|non-commercial|noncommercial|\bnd\b|no-?deriv/.test(s)) return false;
  return /public domain|^pd|\bpd\b|cc0|cc[- ]?by|gfdl|free art|copyleft/.test(s);
}

function stripHtml(value) {
  return String(value == null ? '' : value)
    .replace(/<[^>]*>/g, ' ')
    .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&#0?39;|&apos;/g, "'").replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function extFromUrl(url) {
  const clean = String(url).split('?')[0];
  const match = /\.(jpe?g|png|webp|gif|svg)$/i.exec(clean);
  if (!match) return 'jpg';
  const ext = match[1].toLowerCase();
  return ext === 'jpeg' ? 'jpg' : ext;
}

function renderManifest(images) {
  const group = (name) => {
    const keys = Object.keys(images[name] || {});
    if (!keys.length) return `  ${name}: {},`;
    const rows = keys.map((key) => `    ${key}: '${images[name][key]}'`).join(',\n');
    return `  ${name}: {\n${rows}\n  },`;
  };
  return `/* Generated by tools/fetch-art.js on ${new Date().toISOString().slice(0, 10)}.
 *
 * Real image files installed in this repository. Delete this file's entries (or
 * re-run the script) to go back to the drawn artwork. Credits: ATTRIBUTION.md
 */
window.SplendorImages = {
  version: 1,
${group('gems')}
${group('cards')}
${group('nobles')}
  credits: 'ATTRIBUTION.md'
};
`;
}

function renderAttribution(rows) {
  const header = `# Image credits

The code in this repository is MIT licensed (see \`LICENSE\`). The image files under
\`assets/img/\` are not ours: each is listed below with its source and licence, as
reported by the Wikimedia Commons API when \`tools/fetch-art.js\` downloaded it.

Re-running the script rewrites this file. If you replace an image by hand, please
add its credit here too.

| File | Depicts | Source | Author | Licence |
| --- | --- | --- | --- | --- |
`;
  const body = rows.map((r) =>
    `| \`${r.file}\` | ${r.subject} | [${r.sourceLabel}](${r.sourceUrl}) | ${r.author || '—'} | ${r.license} |`
  ).join('\n');
  const footer = `

## Not included

Splendor is designed by Marc André and published by Space Cowboys. The retail
game's card illustrations, noble portraits and logo are copyrighted and are
deliberately **not** used here — do not add them. Everything above is either
public domain or under a free licence that permits redistribution.
`;
  return header + body + footer + '\n';
}

/* --------------------------------------------------------------- network */

async function api(base, params, retries = 3) {
  const url = new URL(base);
  Object.keys(params).forEach((key) => url.searchParams.set(key, params[key]));
  url.searchParams.set('format', 'json');
  url.searchParams.set('formatversion', '2');

  for (let attempt = 0; attempt <= retries; attempt++) {
    const res = await fetch(url, { headers: { 'User-Agent': UA, 'Accept': 'application/json' } });

    if (res.status === 429 || res.status === 503) {
      if (attempt < retries) {
        const retryAfter = res.headers.get('retry-after');
        const delay = retryAfter ? parseInt(retryAfter, 10) * 1000 : (attempt + 1) * 2000;
        await sleep(delay);
        continue;
      }
    }

    if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url.pathname}`);
    
    // Khoảng cách an toàn giữa các lượt gọi
    await sleep(350);
    return res.json();
  }
}

const WIKIPEDIA = 'https://en.wikipedia.org/w/api.php';
const COMMONS = 'https://commons.wikimedia.org/w/api.php';

async function leadImage(title, width) {
  const data = await api(WIKIPEDIA, {
    action: 'query',
    prop: 'pageimages',
    piprop: 'thumbnail|name',
    pithumbsize: width,
    titles: title,
    redirects: 1
  });
  const page = (data.query && data.query.pages && data.query.pages[0]) || null;
  if (!page || page.missing || !page.thumbnail) return null;
  return {
    title: page.title,
    url: page.thumbnail.source,
    fileName: page.pageimage ? `File:${page.pageimage}` : null
  };
}

async function fileCredit(fileTitle) {
  if (!fileTitle) return null;
  const data = await api(COMMONS, {
    action: 'query',
    prop: 'imageinfo',
    iiprop: 'extmetadata|url',
    titles: fileTitle
  });
  const page = (data.query && data.query.pages && data.query.pages[0]) || null;
  const info = page && page.imageinfo && page.imageinfo[0];
  if (!info) return null;
  const meta = info.extmetadata || {};
  const pick = (key) => (meta[key] && meta[key].value) || '';
  return {
    license: stripHtml(pick('LicenseShortName')) || 'unknown',
    author: stripHtml(pick('Artist')) || stripHtml(pick('Credit')),
    descriptionUrl: info.descriptionurl || `https://commons.wikimedia.org/wiki/${encodeURIComponent(fileTitle)}`
  };
}

async function searchFiles(query, width, limit) {
  const data = await api(COMMONS, {
    action: 'query',
    generator: 'search',
    gsrnamespace: 6,
    gsrsearch: query,
    gsrlimit: limit || 12,
    prop: 'imageinfo',
    iiprop: 'extmetadata|url',
    iiurlwidth: width
  });
  const pages = (data.query && data.query.pages) || [];
  return pages.map((page) => {
    const info = (page.imageinfo && page.imageinfo[0]) || {};
    const meta = info.extmetadata || {};
    const pick = (key) => (meta[key] && meta[key].value) || '';
    return {
      title: page.title,
      url: info.thumburl || info.url,
      mime: info.mime || '',
      license: stripHtml(pick('LicenseShortName')) || 'unknown',
      author: stripHtml(pick('Artist')) || stripHtml(pick('Credit')),
      descriptionUrl: info.descriptionurl || ''
    };
  }).filter((f) => f.url && !/svg/i.test(f.mime));
}

async function download(url, destination, retries = 2) {
  for (let attempt = 0; attempt <= retries; attempt++) {
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (res.status === 429 && attempt < retries) {
      await sleep(2000 * (attempt + 1));
      continue;
    }
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    const buffer = Buffer.from(await res.arrayBuffer());
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, buffer);
    await sleep(250);
    return buffer.length;
  }
}

/* ------------------------------------------------------------------ main */

function parseArgs(argv) {
  const flags = new Set(argv.filter((a) => a.startsWith('--')));
  const wantNobles = flags.has('--nobles') || !(flags.has('--gems'));
  const wantGems = flags.has('--gems') || !(flags.has('--nobles'));
  return {
    nobles: wantNobles,
    gems: wantGems,
    dryRun: flags.has('--dry-run'),
    help: flags.has('--help') || flags.has('-h')
  };
}

const HELP = `Splendor art fetcher

  node tools/fetch-art.js [--nobles] [--gems] [--dry-run]

  --nobles    public-domain portraits for the ten noble tiles
  --gems      photographs of cut stones for the six gem tokens
  --dry-run   report what would be downloaded, write nothing
  --help      this text
`;

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help) { process.stdout.write(HELP); return 0; }

  if (typeof fetch !== 'function') {
    console.error('This script needs Node 18 or newer (global fetch).');
    return 1;
  }

  const images = { gems: {}, cards: {}, nobles: {} };
  const credits = [];
  let failures = 0;

  if (opts.nobles) {
    console.log('\nNoble portraits (public-domain paintings)\n');
    for (const id of Object.keys(NOBLES)) {
      const noble = NOBLES[id];
      let done = false;
      for (const title of noble.titles) {
        try {
          const lead = await leadImage(title, 520);
          if (!lead) { console.log(`  -- ${noble.name}: no lead image on "${title}"`); continue; }
          const credit = await fileCredit(lead.fileName);
          const license = (credit && credit.license) || 'unknown';
          if (!isFreeLicense(license)) {
            console.log(`  !! ${noble.name}: refused "${license}" (${lead.fileName})`);
            continue;
          }
          const rel = `assets/img/nobles/${id}.${extFromUrl(lead.url)}`;
          if (opts.dryRun) {
            console.log(`  ok ${noble.name} -> ${rel} [${license}]`);
          } else {
            const bytes = await download(lead.url, path.join(ROOT, rel));
            console.log(`  ok ${noble.name} -> ${rel} (${Math.round(bytes / 1024)} KB) [${license}]`);
          }
          images.nobles[id] = rel;
          credits.push({
            file: rel, subject: noble.name,
            sourceLabel: lead.fileName || lead.title,
            sourceUrl: (credit && credit.descriptionUrl) || `https://en.wikipedia.org/wiki/${encodeURIComponent(lead.title)}`,
            author: credit && credit.author, license
          });
          done = true;
          break;
        } catch (err) {
          console.log(`  !! ${noble.name}: ${err.message}`);
        }
      }
      if (!done) failures++;
    }
  }

  if (opts.gems) {
    console.log('\nGem photographs (free-licence Commons files)\n');
    for (const color of Object.keys(GEM_QUERIES)) {
      try {
        const found = await searchFiles(GEM_QUERIES[color], 512, 14);
        const usable = found.filter((f) => isFreeLicense(f.license));
        if (!usable.length) {
          console.log(`  !! ${color}: nothing free-licensed among ${found.length} results`);
          failures++;
          continue;
        }
        const pick = usable[0];
        const rel = `assets/img/gems/${color}.${extFromUrl(pick.url)}`;
        if (opts.dryRun) {
          console.log(`  ok ${color} -> ${rel} [${pick.license}] ${pick.title}`);
        } else {
          const bytes = await download(pick.url, path.join(ROOT, rel));
          console.log(`  ok ${color} -> ${rel} (${Math.round(bytes / 1024)} KB) [${pick.license}] ${pick.title}`);
        }
        images.gems[color] = rel;
        credits.push({
          file: rel, subject: color + ' gem',
          sourceLabel: pick.title,
          sourceUrl: pick.descriptionUrl || `https://commons.wikimedia.org/wiki/${encodeURIComponent(pick.title)}`,
          author: pick.author, license: pick.license
        });
      } catch (err) {
        console.log(`  !! ${color}: ${err.message}`);
        failures++;
      }
    }
  }

  const installed = Object.keys(images.gems).length + Object.keys(images.nobles).length;
  if (opts.dryRun) {
    console.log(`\nDry run: ${installed} image(s) would be installed, ${failures} unresolved.`);
    return failures ? 1 : 0;
  }
  if (!installed) {
    console.log('\nNothing was installed, so the manifest is left alone.');
    return 1;
  }

  fs.writeFileSync(path.join(IMG_DIR, 'manifest.js'), renderManifest(images));
  fs.writeFileSync(path.join(ROOT, 'ATTRIBUTION.md'), renderAttribution(credits));
  console.log(`\nInstalled ${installed} image(s).`);
  console.log('  assets/img/manifest.js    rewritten');
  console.log('  ATTRIBUTION.md            rewritten');
  if (failures) console.log(`  ${failures} item(s) could not be resolved — the drawing is used for those.`);
  return 0;
}

if (require.main === module) {
  main().then((code) => process.exit(code)).catch((err) => {
    console.error('\nfetch-art failed:', err.message);
    process.exit(1);
  });
}

module.exports = {
  NOBLES, GEM_QUERIES,
  isFreeLicense, stripHtml, extFromUrl, renderManifest, renderAttribution, parseArgs
};
